// <auto-generated />
using CardholderManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cardholders.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CardholderManagementSystem.Models.Cardholder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 101L);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<long>("TransactionCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Cardholders");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "11 Nexi St",
                            FirstName = "Dragan",
                            LastName = "Jurić",
                            PhoneNumber = "+38591234567",
                            TransactionCount = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Address = "34 Nexi St",
                            FirstName = "Matej",
                            LastName = "Brlec",
                            PhoneNumber = "+38591876543",
                            TransactionCount = 0L
                        },
                        new
                        {
                            Id = 3L,
                            Address = "65 Nexi St",
                            FirstName = "Marija",
                            LastName = "Štefić",
                            PhoneNumber = "+38591876544",
                            TransactionCount = 0L
                        },
                        new
                        {
                            Id = 4L,
                            Address = "65 Nexi St",
                            FirstName = "Kristina",
                            LastName = "Sardelić",
                            PhoneNumber = "+38591111222",
                            TransactionCount = 0L
                        },
                        new
                        {
                            Id = 5L,
                            Address = "New Nexi St",
                            FirstName = "Marina",
                            LastName = "Capan",
                            PhoneNumber = "+38593344556",
                            TransactionCount = 0L
                        });
                });

            modelBuilder.Entity("CardholderManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
